about("𝗧𝗲𝗹𝗲𝗴𝗿𝗮𝗺'𝘀 𝗠𝗼𝘀𝘁 𝗔𝗱𝘃𝗮𝗻𝗰𝗲𝗱 𝗠𝘂𝘀𝗶𝗰 𝗕𝗼𝘁 𝗦𝘂𝗽𝗲𝗿𝗙𝗮𝘀𝘁 || 𝗖𝗵𝗲𝗰𝗸𝗼𝘂𝘁 𝗔𝗻𝗱 𝗝𝗼𝗶𝗻 @The_Flirting_Hub 🌹")
name("𝗬𝗨𝗞𝗞𝗜 ✘ 𝗧𝗙𝗛 [4]")
type("Five, Six, seven, eight, nine, ten,")
USERNAME_BOTS("@Yukki_Ten_Bot")
pass (teamyukki) YUKKI(1)("@Yukki_Nine_Bot,")
           YUKKI(2)("@Yukki_Eight_Bot,")
            YUKKI(3)("@Yukki_Seven_Bot,")
             YUKKI(4)("@Yukki_Six_Bot,")
              YUKKI(5)("@Yukki_Five_Bot,")
               YUKKI(6)("@Yukki_Four_Bot,")
                YUKKI(7)("@Yukki_Three_Bot,")
                 YUKKI(8)("@Yukki_Two_Bot,")
                  YUKKI(9)("@Yukki_Music_Official_Bot")
                   YUKKI(10)("@Yukii_One_Bot,")
                  (close.bot).fill(__bot_username__)opne exit><(/reboot){var.eval})
class(None,)keyButtons_inline(mode=true,/ False,).off
